### ISSUE TITLE
[FEATURE] Arithmetics

### ISSUE THREAD

**Issue by georg-schwarz** [jvalue/jayvee#271]
## User Story
1. As a {Jayvee user}
2. I want {to use arithmetic expressions}
3. So that {I can calculate property values instead of doing the calculation myself}

## User Acceptance Criteria
- [ ] classic addition/multiplication operators `+`, `-`, `*`, `/` are supported
- [ ] modulo operator `%` is supported
- [ ] power and root operators are supported
- [ ] operators and their precedence is documented
- [ ] handling of different data types is documented

## Examples
- `2 / 3` instead of `0.666666`
- `exp(2, 7)` pr `2^7` instead of `128`

## Notes
- This feature builds into value transformations (e.g. "take cell A7 and add 7") which are not yet part of this issue.

## Open Discussions
- [ ] How is the interplay of integers and decimals handled?
- [ ] Which operators for power and root functionality?

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
Here my suggestions to the open points. @felix-oq @rhazn Looking forward to your feedback :) 

## How is the interplay of integers and decimals handled?

Felix suggested that arithmetic operations that produce a decimal number (e.g. division with a rest) are **never** interpreted as integer. Instead, we supply unary operators `floor`, `ceil`, and `round` to turn a decimal to an integer. I'd also **not** introduce casting functionality but require the use of those unary operators.

## Which operators for power and root functionality?

I'd suggest to use two bidirectional operators with the postfix notation (like a method call): `pow` and `root`. Personally, I think the `^` is a little weird, and handling power and root differently seems even weirder to me as there is no common operator sign for it. We could introduce one, though, e.g. `§` - but probably not a good idea.

**Comment by rhazn** [comment]
I am not clear what this describes, you talk about property values in the story description but the UAC seem to refer to value transformations? Also, shouldn't this be in a RFC?

In general I agree with both of your open point suggestions though. The first one is unclear (you write 'produce a decimal number (division with a rest)' but then write 'never', I assume from that 6 / 3 would result in the decimal 2.0, not the integer 2 but according to your first point it does not produce a decimal number as it does not have a rest?

**Comment by felix-oq** [comment]
> I am not clear what this describes, you talk about property values in the story description but the UAC seem to refer to value transformations?

We plan to gradually introduce expressions and arithmetics into the language, so we're able to tackle value transformations (#213) soon. The very first step is #272.

The only place where expressions currently make sense is in places where values are expected (i.e. property values). So for instance, the goal is that users are able to express `lowerBound: 2/3;` instead of having to write `lowerBound: 0.666666666667;`.

> Also, shouldn't this be in a RFC?

The language concept for value transformations definitely requires an RFC. Before it, we may also need one for arithmetic expressions, to clarify the open points that @georg-schwarz pointed out above (only required if we don't come to an agreement here).

**Comment by felix-oq** [comment]
In general I also like the proposition from @georg-schwarz. Can you give some examples on how you imagine the syntax for the functions (`floor`, `ceil`, `round`, `pow` and `sqrt`) to look like?

I could think of them being keywords of the language, so expressions may look like `floor 5.3` or `floor(5.3)`.
Alternatively, they could be called like functions in programming languages, e.g. `(5.3).floor()`. That way they would not "pollute" our namespace with keywords but the syntax is not really intuitive.

Also, in that regard, `pow` is a special case, because it is a binary operator (base and exponent). How could that look like?

**Comment by rhazn** [comment]
Hmm, then I largely agree (I assume Georgs initial points are: Always keep decimal, even for results that have no rest and prefix notation, not postfix? If so I agree on both.)

I kind of feel we might run into slowly implementing all these things one by one instead of embedding a language into Jayvee that could do all these things. I mentioned KCL earlier and they actually seem to have a comparison here: https://github.com/KusionStack/KCLVM#how-to-choose. But, reading that comparison, it seems to me they do way more than "just" evaluating boolean and arithmetic expressions. So, to summarize my train of though: This issue probably makes sense 😅 .

**Comment by rhazn** [comment]
Even though, with this discussion, I still have no idea why we do not do it in a RFC and revert to an issue. I thought you talked this through in a meeting beforehand. For a slower discussion with examples I'd encourage the RFC and for a faster one a meeting 😅 .

**Comment by georg-schwarz** [comment]
Closed in favor of RFC process
