### ISSUE TITLE
[BUG] File picker should not crash for paths starting with a dot

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#381]
## Steps to reproduce
1. Use a file `FilePicker` block with a path for an existing file, starting with a dot: `./data.csv`

## Description
- Expected: The `FilePicker` selects the file
- Actual: `error: An unknown error occurred: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  (0, assert_1.strict)(file instanceof jayvee_execution_1.BinaryFile)`

## Notes
- using the path without a dot (`/data.csv`) works
- Reported in studon: https://www.studon.fau.de/studon/goto.php?target=frm_5003028_338627_989410&client_id=StudOn

**Comment by TungstnBallon** [comment]
So, if I understand this correctly, the only way to use `FilePicker` is after a block with the `FileSystem` output type.

I'm still struggling to understand what a dot at the start of a path is supposed to mean in this context. Usually the dot is a shorthand to the current working directory, but that directory might be completely unrelated to the `Filesystem`'s root.
```
a/
└── cars.zip (<- ArchiveInterpreter sets the FileSystem's root here)
   └── cars.csv
b/
└── c/ (<- working directory might be here)
   └── pipeline.jv
```


At first I did confuse `FilePicker` with `LocalFileExtractor`, maybe that's the actual problem here?

**Comment by rhazn** [comment]
Yeah, this is related to the pipeline model, not the actual filesystem of the user. So the `FilePicker`s input is a `FileSystem`. The path is in relation to that `FileSystem`, not to the file system the model is executed from. The working directory for `.` is the root of that `FileSystem`. 

So for `cars.zip`, the paths `./cars.csv` and `/cars.csv` both reference the `cars.csv` file in it. This is totally independent from where the model is executed from.

The `LocalFileExtractor` is a loader block that loads a file from the local file system, so for that block the path needs to reference an actual file from the users file system. But that block is unrelated to the `FilePicker`.
